name: Deploy to Development

concurrency:
  group: terraform-dev
  cancel-in-progress: false

on:
  push:
    branches: [dev]
    paths:
      - "app/**"
  workflow_dispatch:
    inputs:
     environment:
      type: choice
      options: [dev]
      default: dev


permissions:
  contents: read
  id-token: write   # AWS OIDC
  pull-requests: write

env:
  AWS_REGION: eu-west-2
  ENV_NAME: dev
  TG_DIR: infra/live/dev
  APP_DIR: app
  ECR_REPO: url-shortener

jobs:
  validate_and_plan:
    name: Validate, Lint, Snyk, Plan (Dev)
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4


       # ---- AWS OIDC login for plan 
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEV_ROLE_ARN1 }}
          aws-region: ${{ env.AWS_REGION }}

      # ---- Terraform toolchain ----
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.0"
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v3
        with:
          terragrunt-version: "0.54.22"

      - name: Terragrunt init
        working-directory: ${{ env.TG_DIR }}
        run: terragrunt init --terragrunt-non-interactive

      #- name: Debug working directory
       # run: |
       #   pwd
        #  ls -la

      - name: Terraform fmt (check)
        working-directory: infra
        run: terraform fmt -check -recursive



      # ---- TFLint ----
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
           tflint_version: v0.50.3

      - name: TFLint init
        working-directory: infra
        run: tflint --init

      - name: TFLint
        working-directory: infra
        run:  tflint --recursive --force


      # ---- Snyk (IaC scan) ----
      - name: Setup Snyk
        uses: snyk/actions/setup@master

      - name: Snyk IaC test
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk iac test --org=${{ secrets.SNYK_ORG }} --severity-threshold=high
      - name: Debug GitHub context
        run: |
         echo "event=${{ github.event_name }}"
         echo "ref=${{ github.ref }}"
         echo "ref_name=${{ github.ref_name }}"


      - name: Terragrunt debug (what inputs/vars are used)
        working-directory: ${{ env.TG_DIR }}
        run: |
             terragrunt render-json --terragrunt-non-interactive | head -n 200

      - name: Terragrunt inputs debug
        working-directory: ${{ env.TG_DIR }}
        run: |
            terragrunt render-json --terragrunt-non-interactive > tg.json
            jq -r '.inputs | {
            availability_zones,
            public_subnets,
            private_subnets,
            db_subnets
             }' tg.json

     

      - name: Terragrunt plan
        working-directory: ${{ env.TG_DIR }}
        run: terragrunt plan --terragrunt-non-interactive -no-color -out="$GITHUB_WORKSPACE/${{ env.TG_DIR }}/tfplan" 


      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-dev1
          path: ${{ env.TG_DIR }}/tfplan
          if-no-files-found: error

  apply:
    name: Apply (Dev)
    runs-on: ubuntu-latest
    environment: dev
    needs: validate_and_plan
    if: >
      (github.ref == 'refs/heads/dev' && github.event_name == 'push')
      || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.0"

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v3
        with:
          terragrunt-version: "0.54.22"

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEV_ROLE_ARN1 }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download tfplan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan-dev1
          path: ${{ env.TG_DIR }}

      - name: Debug working directory
        run: |
          pwd
          ls -la

      - name: Terragrunt init
        working-directory: ${{ env.TG_DIR }}
        run: terragrunt init --terragrunt-non-interactive
          
      - name: Terragrunt debug (what inputs/vars are used)
        working-directory: ${{ env.TG_DIR }}
        run: |
             terragrunt render-json --terragrunt-non-interactive | head -n 200
      - name: Terragrunt inputs debug
        working-directory: ${{ env.TG_DIR }}
        run: |
            terragrunt render-json --terragrunt-non-interactive > tg.json
            jq -r '.inputs | {
            availability_zones,
            public_subnets,
            private_subnets,
            db_subnets
             }' tg.json

      - name: Terragrunt apply (Dev)
        working-directory: ${{ env.TG_DIR }}
        run: terragrunt apply --terragrunt-non-interactive -auto-approve tfplan
