name: Destroy dev

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type destroy-dev to confirm"
        required: true
permissions:
  id-token: write
  contents: read

env:
  TF_VERSION: "1.9.8"
  AWS_REGION: "eu-west-2"  
  Tr_VERSION: "0.54.22"
  TG_DIR: infra/live/dev

concurrency:
  group: terraform-dev-destroy
  cancel-in-progress: false



jobs:
  destroy:
    if: ${{ github.event.inputs.confirm == 'destroy-dev' }}
    runs-on: ubuntu-latest
    environment: dev

    steps:

     # ---- AWS OIDC login 
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEV_ROLE_ARN1 }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v3
        with:
          terragrunt-version: ${{ env.Tr_VERSION }}

      - name: Terragrunt init
        working-directory: ${{ env.TG_DIR }}
        run: terragrunt init --terragrunt-non-interactive

      - name: Terragrunt destroy (Dev)
        working-directory: ${{ env.TG_DIR }}
        run: terragrunt destroy --terragrunt-non-interactive -auto-approve
